### PR TITLE
UI-Changed

### PR DESCRIPTION
**Pull request by sujitIwale**
Sign in and sign up changed 
added some buttons

### CODE REVIEW

**Comment by stephin007** [comment]
Hey @sujitIwale , Few Observations:
Things that i liked
- SignIn 
- SignUp page

Things which will need a bit of change.
- Please align the follow button to the right of the name of the user.
- Can you please remove the button of post as a text rather please try to add an icon which basically means to post/send.

Rest, everything is good.... It would be better if you do a single PR for SIgnIn and SignUp, i liked it ..i will merge it ASAP.
And raise another PR after you are done with my suggestions!

**Comment by sujitIwale** [comment]
> Hey @sujitIwale , Few Observations:
> Things that i liked
> 
> * SignIn
> * SignUp page
> 
> Things which will need a bit of change.
> 
> * Please align the follow button to the right of the name of the user.
> * Can you please remove the button of post as a text rather please try to add an icon which basically means to post/send.
> 
> Rest, everything is good.... It would be better if you do a single PR for SIgnIn and SignUp, i liked it ..i will merge it ASAP.
> And raise another PR after you are done with my suggestions!

will I need to close this PR?

**Comment by stephin007** [comment]
@sujitIwale That i will close, please dont do  anything , unless not told to! :)

**Comment by stephin007** [comment]
Sorry @sujitIwale , your PR is too confusing, Please remove the unwanted css of the profile and posts and then make a new branch with only the signin and signup chnages only and then raise another PR.
please do the neccessary chnages :)

**Comment by LuckyPigeon** [comment]
refer to #4

**Pull request closed without merging**
